### PR TITLE
Add support for cannon-es-debugger

### PR DESCRIPTION
**Pull request by elisherer**
Addresses #21 

image

image

## Usage

Add a `debug` prop to the `<Physics />` component.

e.g.
```jsx
ReactDOM.render(
  <Canvas>
    <Physics debug>
      <Plane />
      <Cube />
    </Physics>
  </Canvas>,
  document.getElementById('root')
)
```

## Tech notes

- I externalized the `propsToBody` algorithm from the worker, so the `useBody` hook could fill the `debugInfo` with its own bodies (so we could use `cannon-es-debugger` as-is)
- The debugger component has its own "dummy" `THREE.Scene` for the same purpose of using the debugger as-is.
- The debug prop can't be switched on and off since the solution relies on "monkey patching" the `useBody` hook. If switched off then no body information is collected.

### CODE REVIEW

**Comment by stockHuman** [comment]
Thanks for this, @elisherer! Instant collider view is very handy to have.

@marcofugaro do you want to weigh in on this? I'm not entirely sold on the idea of a debugger with erroneous representations (as a limitation) like in the Vehicle demo or even the demos pictured above, where the debug representation isn't accurate to the physics model.

**Comment by elisherer** [comment]
@stockHuman, any other comments on this PR? I'm working with that version of use-cannon already and it saves me a lot of time building my bodies (can't see any other way of doing it).
About your comment, I am using cannon-es-debugger as-is and what ever "erroneous representations" are part of it and will be fixed as it is a dependency. We can add it as a peer dependency instead of a dependency to allow upgrading the debugger without relying on use-cannon (but it will mean that every installation of use-cannon will require cannon-es-debugger);

**Comment by stockHuman** [comment]
Hey @elisherer, I've spoken to Paul, I think we'll merge. :)

**Comment by drcmda** [comment]
@elisherer thanks! i made some adjustments:

- it's completely optional and won't bring in a full cannon-es for use-cannon users
- it's faster as it won't poll through react.setState to figure out new bodies

**Comment by elisherer** [comment]
@drcmda, very cool! I haven't figured I made `cannon-es` be bundled twice. Good idea to split it up.
I see you went with black as the default 😁

**Pull request merged**
