### PR TITLE
Convert worker into static import & update deps and demos

### PR DESCRIPTION
**Pull request by stockHuman**
Hello folks. :)

This implements @darwin's [fork](https://github.com/darwin/use-cannon/commit/81fb03fda4aaf31b60085ece9118cb02183fce74) (#132), which solves #143, and potentially more. It also deals with the cyclical dependency warning.

Additionally, the demos have been cleaned up (removed `sRGB` prop, corrected an import that assumed a dev environment, &c) and some dependencies updated.

### CODE REVIEW

**Comment by stockHuman** [comment]
My only question before merging this is about the decision to lazy load; if this was a performance concern that I'm not noticing or something else. Thanks :)

**Comment by drcmda** [comment]
sorry for late review, but if it works, merge it! :-) @stockHuman

**Review by drcmda — APPROVED** [review]

**Comment by drcmda** [comment]
also @darwin if you want to work officially on use-cannon, i think everyone would like that!

**Comment by stockHuman** [comment]
@drcmda No problem at all! I can see how alive the Discord is, and that's surely not the least of what's on your plate. Anyway, thanks :)

**Pull request merged**
