### PR TITLE
fixes bodies sync bug

### PR DESCRIPTION
**Pull request by simonghales**
This should resolve this issue: https://github.com/pmndrs/use-cannon/discussions/96

fixes a small bug where whenever the bodies need to be synchronized, the next 'frame' update might arrive before the 'sync' update is received and processed.

This is fixed by bundling the data originally sent via the 'sync' update, as part of the 'frame' update.

### CODE REVIEW

**Comment by simonghales** [comment]
Unfortunately I couldn't get the examples folder to work locally, so I haven't managed to verify this myself just yet. I should be able to do so tonight, but figured I'd make the PR request now in case somebody wanted to review it before then.

**Comment by stockHuman** [comment]
Hey Simon, thanks for this PR.

If you get your branch up to date with `master` and jump straight to the chain demo, you'll see this unfortunately breaks things with _bodies[uuid] is undefined_. I'd tried what you'd written in the discord and simply thought I was implementing it wrong when I saw the same result.

**Comment by simonghales** [comment]
I will take a look!

**Comment by simonghales** [comment]
@stockHuman the chain demo is working for me now

**Comment by stockHuman** [comment]
Awesome, thanks for the fix.

**Pull request merged**
