### PR TITLE
Automatic linting

### PR DESCRIPTION
**Pull request by bjornstar**
We're constantly running into linting issues, this is a solved problem we just need to turn it on.

This enables `prettier` and `eslint` and adds pre-commit hooks as well as running CI on github.

### CODE REVIEW

**Comment by bjornstar** [comment]
There's still a bunch of lint issues that need to be resolved, I have only committed the prettier fixes.

**Comment by bjornstar** [comment]
Just a few lint warnings now, this should be good to go

**Comment by bjornstar** [comment]
After this I should have a PR for converting propsToBody to typescript.

**Comment by stockHuman** [comment]
Was there a rationale for setting the print-width to 160?

**Pull request merged**
