### PR TITLE
fix pong demo

### PR DESCRIPTION
**Pull request by dreammonkey**

### CODE REVIEW

**Comment by stockHuman** [comment]
Hey Diederik, thanks for this, and for your previous pull I seem to have rolled over.

This seems to fix things, but would you know if this is original to the earlier demo? The ball seems to sink into the paddle.
image

**Comment by dreammonkey** [comment]
Good catch ! 😎

I honestly hadn't noticed, if it wasn't in the original demo chances are small that my contribution causes this to happen (you'll see my point when you look at the changes I've made)

I was just happy the errors where gone, but there could be more going on with this demo then I expected. Probably better to leave it to the original author to fix.

**Comment by dreammonkey** [comment]
I just saw this: https://github.com/pmndrs/use-cannon/discussions/94#discussioncomment-33641

Should be fairly easy to fix

**Comment by stockHuman** [comment]
Thanks, Diederik. Look how far the lib has come - already suffering from code rot! :)

Fixed [here](https://github.com/pmndrs/use-cannon/commit/0ce9d038e7a1e723e7f81369b048e38d4b8e021c)

**Pull request closed without merging**
