### PR TITLE
Fix loop performance

### PR DESCRIPTION
**Pull request by David-Beale**
1.3.1 introduced some small performance issues.
This gets everything working perfectly again for me

### CODE REVIEW

**Comment by drcmda** [comment]
can you measure performance regressions? it should actually be faster because it's not using two raf's which this pr would go back to.

**Comment by David-Beale** [comment]
I'm wondering if the logic is out of sync by a frame.  It wouldn't be noticeable to the naked eye, but my AI has been trained using cannon-js, and worked perfectly before 1.3.1. Afterwards, it's unable to make certain moves. I assumed it was lag, but could also be because of a 1 frame delay.

**Comment by David-Beale** [comment]
I'm not very familiar with useFrame, but my theory is that it posts a "step" message 60 times a second regardless of any "backlog" in the cannon-js thread. So I'm guessing it's likely that it's sending another step request before the buffer positions/quaternions have been updated.

In previous versions, the next step message can only ever be sent once the frame message is received and the positions/quaternions have been updated.

**Comment by David-Beale** [comment]
Comparison of the two:

https://www.youtube.com/watch?v=MxmzP7VsMYU

Originally it reacts at the perfect moment to barely make the turn.

Now it seems to be reacting a fraction of a second late.

**Comment by drcmda** [comment]
useframe binds the component to the global render-loop. if a component needs to execute something in a loop it usually should be done in there in order to not cause raf requests. but what you say seems valid. i just wonder where these huge raf/onmessage blobs come from if we switch to the old version, they seem pretty threatening to me.

**Comment by drcmda** [comment]
redoing that part rn, it can copy over positions inside onmessage

**Comment by David-Beale** [comment]
Interestingly, simply changing the loop render priority from -1 to Infinity solves my problem. Would that mess anything up?

**Comment by drcmda** [comment]
Yes, that would only work if you work with fixed models, if you are something at runtime it should be stuck. But I have it working, I test a little more and then push.

**Comment by David-Beale** [comment]
awesome, thanks

**Comment by drcmda** [comment]
btw @David-Beale your game looks interesting! you want to join https://github.com/pmndrs/racing-game ?

**Comment by David-Beale** [comment]
> btw @David-Beale your game looks interesting! maybe think about joining https://github.com/pmndrs/racing-game

Thanks. Yeah I'll definitely have a look once I'm finished with this project.

**Comment by David-Beale** [comment]
I've figured out a work around for my problem. I just need to make sure my neural network activates before the loop function. So setting my component render priority to -2 fixes everything without having to edit the library.

**Comment by David-Beale** [comment]
Ignore all the nonsense about "backlogs". It's just a timing issue. All component interactions seem to be delayed until the next frame unless manually adjusting the render priority. 

I feel like setting the loop render priority to Infinity should work. I'm still able to add and remove objects on the fly without any problems

**Comment by David-Beale** [comment]
Could also be because the subscriptions are out of sync. Sorry, lots of guess work.

**Comment by drcmda** [comment]
i've updated the lib. now it writes to the objects inside onmessage and all this framing back and forth goes away. i also use matrixautoupdate=false and matrix instead of position and rotation by quaternions, that should also be a little faster.

**Comment by David-Beale** [comment]
Thanks. Doesn't solve my problem though, I still need a manual render priority < 0  :pensive: . 

Also introduced a breaking change: The position and quaternion in the mesh object are no longer updated:
image

I need to switch to getWorldPosition() or a subscription, but perhaps I have should have been doing that anyway.

**Comment by drcmda** [comment]
that's odd, i mean, what better place than update objects in onmessage instead of a frame late. the position/quat may be collateral, but i think it should probably have been matrix all along because it's faster and nothing else but physics can place these objects.

**Comment by David-Beale** [comment]
I think what's happening is:

values1 => step => apply forces(values1) => update values(values 2) => step => apply forces(values2) 

whereas I need it to be:

values1 => apply forces(values1) => step => update values(values 2) =>apply forces(values2) => step 

I admit it makes no difference in 99.9% of cases so I'm happy to use manual render priority as a fix.

re position/quat. I was just using them for my camera target, so makes sense to switch to getWorldPosition() anyway.

I really appreciate your time and help with this :pray: . Happy to close this PR.

**Pull request closed without merging**
